on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        # Test on fewer Go versions to avoid bitwarden.com rate limits.
        # go-version: [1.15.x, 1.16.x]
        go-version: [1.16.x]
        # Since the PATH hack below doesn't work on Windows.
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Linux deps
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y --no-install-recommends dbus libsecret-tools
    - name: Install portable deps
      run: go install rsc.io/2fa

    - name: Test
      run: PATH="$(go env GOPATH)/bin:$PATH" go test -v ./...
      env:
        PASSWORD_NOTFA: ${{ secrets.PASSWORD_NOTFA }}
        PASSWORD_WITHTFA: ${{ secrets.PASSWORD_WITHTFA }}
        TFAKEY: ${{ secrets.TFAKEY }}
